### ISSUE TITLE
Some comment to Fuzzy matching - Kenya

### ISSUE THREAD

**Issue by LuciaSegovia** [TomCodd/Fuzzy_Search#2]
I have tried the fuzzy matching function and it's super cool! I have some comments 🙂

1. I felt that the matches should be done the other way around. I.e., Kenya FCT sould be driving the matches, as the first column, and the Dictionary the second. 

2. It doesn't allow me to click "all the matche idenfied" if I leave MAPS dictionary items without a match. But there are items for which none of the proposed items are correct.

**Comment by TomCodd** [comment]
Hi Lucia,

Thanks for the comments! :) 

1. This has now been switched around :)

2. This shouldn't be the case - the code should stop you continuing if you don't have a confidence value entered for a match you've accepted, but it should let you aside from that - I'll look into it!
